name: Build & Test

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master, ci ]

env:
  CARGO_TERM_COLOR: always
  ABY_SOURCE: "./../ABY"
  KAHIP_SOURCE: "./../ABY"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update; sudo apt-get install zsh cvc4 libboost-all-dev libssl-dev coinor-cbc coinor-libcbc-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: Initialize third_party libraries
      run: make install_deps
    - name: Cache third_party build
      uses: actions/cache@v2
      with:
        path: |
          ${ABY_SOURCE}/build
          ${KAHIP_SOURCE}/build
          ${KAHIP_SOURCE}/deploy
        key: ${{ runner.os }}
    - name: Build third_party libraries
      run: make build_deps
    - name: Typecheck
      run: cargo check
    - name: Check format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy
    - name: Build
      run: make build
    - name: Run tests
      run: make test
